

DROP TABLE IF EXISTS `ALBUM` ;
CREATE TABLE `ALBUM` (
    `ID` INT AUTO_INCREMENT PRIMARY KEY,
    `TITLE` VARCHAR(128) NOT NULL   ,
    `ARTIST` VARCHAR(32) NOT NULL   ,
    `ISSUE_DATE` DATE   ,
    `GENRE` CHAR(2)     ,
    `COVER_PHOTO` BLOB  ,
    `CREATE_AUTHOR` VARCHAR(32),
    `CREATE_DATETIME` TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    `UPDATE_AUTHOR` VARCHAR(32),
    `UPDATE_DATETIME` TIMESTAMP  DEFAULT CURRENT_TIMESTAMP
);



DROP TABLE IF EXISTS `ALBUM_TRACK` ;
CREATE TABLE `ALBUM_TRACK` (
    `ALBUM_ID` INT NOT NULL ,
    `TRACK_NO` INT NOT NULL ,
    `TRACK_NAME` VARCHAR(128) NOT NULL  ,
    `PLAY_TIME` DECIMAL(4,2)    ,
    `CREATE_AUTHOR` VARCHAR(32),
    `CREATE_DATETIME` TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    `UPDATE_AUTHOR` VARCHAR(32),
    `UPDATE_DATETIME` TIMESTAMP  DEFAULT CURRENT_TIMESTAMP
);
ALTER TABLE `ALBUM_TRACK` ADD CONSTRAINT `PK_ALBUM_TRACK` PRIMARY KEY ( ALBUM_ID ,TRACK_NO ) ;



DROP TABLE IF EXISTS `ALBUM_CONTRIBUTOR` ;
CREATE TABLE `ALBUM_CONTRIBUTOR` (
    `ALBUM_ID` INT NOT NULL ,
    `TRACK_NO` INT(128) NOT NULL    ,
    `CONTRIBUTOR` VARCHAR(32) NOT NULL  ,
    `COMMENT` VARCHAR(256)  ,
    `CREATE_AUTHOR` VARCHAR(32),
    `CREATE_DATETIME` TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    `UPDATE_AUTHOR` VARCHAR(32),
    `UPDATE_DATETIME` TIMESTAMP  DEFAULT CURRENT_TIMESTAMP
);
ALTER TABLE `ALBUM_CONTRIBUTOR` ADD CONSTRAINT `PK_ALBUM_CONTRIBUTOR` PRIMARY KEY ( ALBUM_ID ,TRACK_NO ,CONTRIBUTOR ) ;



DROP TABLE IF EXISTS `ALBUM_GENRE` ;
CREATE TABLE `ALBUM_GENRE` (
    `GENRE_ID` CHAR(2) NOT NULL ,
    `GENRE_NAME` VARCHAR(32) NOT NULL   ,
    `COMMENT` VARCHAR(512)  ,
    `CREATE_AUTHOR` VARCHAR(32),
    `CREATE_DATETIME` TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    `UPDATE_AUTHOR` VARCHAR(32),
    `UPDATE_DATETIME` TIMESTAMP  DEFAULT CURRENT_TIMESTAMP
);
ALTER TABLE `ALBUM_GENRE` ADD CONSTRAINT `PK_ALBUM_GENRE` PRIMARY KEY ( GENRE_ID ) ;


